FROM envoyproxy/envoy-dev:latest

RUN apt-get update && apt-get -q install -y \
    curl && apt-get -q install -y net-tools

ADD ./envoy /usr/local/bin/envoy

CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
